"""
Extract coordinates and names for RRB bus stop quays from the full NSR Tiamat export.
Uses SAX streaming to handle the large (400+ MB) XML file.

Usage:
    python scripts/extract_bus_stop_locations.py

Reads:
    - NeTEx2EDIFACT/scripts/check_rrb_quayrefs.py output (inline quay IDs)
    - Nordic source material/tiamat-export-Current-202605081200012583.xml

Writes:
    - Nordic source material/rrb_bus_stop_locations.csv
"""

import xml.sax
import csv
import sys
import re
from pathlib import Path

# -------------------------------------------------------------------
# RRB quay IDs (409 unique NSR:Quay:NNNNN IDs from operator source data)
# Generated by check_rrb_quayrefs.py
# -------------------------------------------------------------------
RRB_QUAY_IDS = set()

def _load_rrb_quay_ids():
    """Load RRB quay IDs from the source zips via the analysis script."""
    # Re-run the quay-ref extraction inline to get the exact set
    import zipfile, xml.etree.ElementTree as ET
    ns = {
        'netex': 'http://www.netex.org.uk/netex',
        'gml': 'http://www.opengis.net/gml/3.2',
    }
    source_dir = Path(__file__).parent.parent / 'Source'
    quay_ids = set()
    for zip_path in sorted(source_dir.glob('*.zip')):
        try:
            with zipfile.ZipFile(zip_path) as z:
                for name in z.namelist():
                    if not name.endswith('.xml'):
                        continue
                    data = z.read(name)
                    try:
                        root = ET.fromstring(data)
                    except ET.ParseError:
                        continue
                    # PassengerStopAssignment / StopAssignment QuayRef
                    for el in root.iter():
                        tag = el.tag.split('}')[-1] if '}' in el.tag else el.tag
                        if tag == 'QuayRef':
                            ref = el.get('ref', '') or el.text or ''
                            ref = ref.strip()
                            if ref.startswith('NSR:Quay:') and '-B-' not in ref and 'BUS' in (el.get('name', '') or ''):
                                quay_ids.add(ref)
                            elif ref.startswith('NSR:Quay:'):
                                quay_ids.add(ref)
        except Exception:
            pass
    return quay_ids


def load_rrb_quay_ids_from_source():
    """
    Parse all operator source zips and collect every NSR:Quay:XXXXX QuayRef that
    is mapped to a bus-type ScheduledStopPoint (identified by BUS_MARKERS in the SSP id).
    Uses the same logic as check_rrb_quayrefs.py.
    """
    import zipfile, xml.etree.ElementTree as ET

    NX = "http://www.netex.org.uk/netex"
    BUS_MARKERS = ("-B-", "-Bus", "-BUS", "-bus", "-b-", "-A_", "-A ")

    source_dir = Path(__file__).parent.parent / 'Source'
    quay_ids = set()

    for zip_path in sorted(source_dir.glob('*.zip')):
        try:
            with zipfile.ZipFile(zip_path) as z:
                # Prefer _Shared files (contain PSA definitions), fall back to all XMLs
                shared = [f for f in z.namelist() if f.startswith('_') and f.endswith('.xml')]
                files_to_scan = shared if shared else [f for f in z.namelist() if f.endswith('.xml')]

                for fname in files_to_scan:
                    data = z.read(fname)
                    if b'PassengerStopAssignment' not in data:
                        continue
                    try:
                        root = ET.fromstring(data)
                    except ET.ParseError:
                        continue
                    for psa in root.iter(f"{{{NX}}}PassengerStopAssignment"):
                        ssp_el = psa.find(f"{{{NX}}}ScheduledStopPointRef")
                        quay_el = psa.find(f"{{{NX}}}QuayRef")
                        if ssp_el is None or quay_el is None:
                            continue
                        ssp_id = ssp_el.get('ref', '')
                        qref = quay_el.get('ref', '')
                        if any(m in ssp_id for m in BUS_MARKERS) and qref.startswith('NSR:Quay:'):
                            quay_ids.add(qref)
        except Exception as e:
            print(f"  Warning: {zip_path.name}: {e}", file=sys.stderr)

    return quay_ids


# -------------------------------------------------------------------
# SAX handler: find Quay elements matching our IDs, capture coordinates
# -------------------------------------------------------------------

class QuayLocHandler(xml.sax.ContentHandler):
    """
    Stream the NeTEx XML and extract Quay coordinates.
    Quay elements have no Name child — the name lives on the parent StopPlace.
    We track the current StopPlace name and apply it to each matching Quay inside it.
    """

    def __init__(self, target_ids):
        super().__init__()
        self.target_ids = target_ids          # set of 'NSR:Quay:NNNNN'
        self.found = {}                        # quay_id -> dict

        # StopPlace context (name applies to all child Quays)
        self._stopplace_name = ''             # name of the enclosing StopPlace
        self._in_stopplace = False
        self._stopplace_depth = 0
        self._in_sp_name = False              # reading StopPlace/Name

        # Quay state
        self._in_quay = False
        self._current_id = None
        self._in_pos = False
        self._in_lon = False
        self._in_lat = False
        self._quay_depth = 0                  # depth inside current Quay element
        self._chars = []

    def _rec(self):
        """Get or create the found record for the current quay."""
        return self.found.setdefault(self._current_id, {
            'quay_id': self._current_id, 'name': '', 'lat': '', 'lon': '', 'gml_pos': ''
        })

    def startElement(self, name, attrs):
        local = name.split(':')[-1]

        # --- StopPlace tracking ---
        if local == 'StopPlace':
            if not self._in_stopplace:
                self._in_stopplace = True
                self._stopplace_name = ''
                self._stopplace_depth = 0
            else:
                self._stopplace_depth += 1
            return

        if self._in_stopplace and not self._in_quay:
            if local == 'Name' and self._stopplace_depth == 0 and not self._in_sp_name:
                self._in_sp_name = True
                self._chars = []
                return

        # --- Quay tracking ---
        if local == 'Quay':
            qid = attrs.get('id', '')
            if qid in self.target_ids:
                self._in_quay = True
                self._current_id = qid
                self._quay_depth = 0
            elif self._in_quay:
                self._quay_depth += 1
            return

        if self._in_quay:
            self._quay_depth += 1
            if local == 'pos':
                self._in_pos = True
                self._chars = []
            elif local == 'Longitude':
                self._in_lon = True
                self._chars = []
            elif local == 'Latitude':
                self._in_lat = True
                self._chars = []

    def endElement(self, name):
        local = name.split(':')[-1]

        # --- StopPlace Name capture ---
        if local == 'Name' and self._in_sp_name:
            self._in_sp_name = False
            self._stopplace_name = ''.join(self._chars).strip()
            self._chars = []
            return

        if local == 'StopPlace':
            if self._stopplace_depth == 0:
                self._in_stopplace = False
                self._stopplace_name = ''
            else:
                self._stopplace_depth -= 1
            return

        # --- Quay element handling ---
        if self._in_quay:
            if local == 'Quay':
                if self._quay_depth == 0:
                    # Finished — record StopPlace name as the stop name
                    rec = self._rec()
                    if not rec['name'] and self._stopplace_name:
                        rec['name'] = self._stopplace_name
                    self._in_quay = False
                    self._current_id = None
                else:
                    self._quay_depth -= 1
            elif local == 'pos' and self._in_pos:
                self._in_pos = False
                pos = ''.join(self._chars).strip()
                self._chars = []
                rec = self._rec()
                rec['gml_pos'] = pos
                parts = pos.split()
                if len(parts) == 2:
                    rec['lat'] = parts[0]
                    rec['lon'] = parts[1]
                self._quay_depth = max(0, self._quay_depth - 1)
            elif local == 'Longitude' and self._in_lon:
                self._in_lon = False
                self._rec()['lon'] = ''.join(self._chars).strip()
                self._chars = []
                self._quay_depth = max(0, self._quay_depth - 1)
            elif local == 'Latitude' and self._in_lat:
                self._in_lat = False
                self._rec()['lat'] = ''.join(self._chars).strip()
                self._chars = []
                self._quay_depth = max(0, self._quay_depth - 1)
            else:
                self._quay_depth = max(0, self._quay_depth - 1)

    def characters(self, content):
        if self._in_sp_name or self._in_pos or self._in_lon or self._in_lat:
            self._chars.append(content)


def main():
    workspace = Path(__file__).parent.parent.parent  # UIC NeTex Profile/
    xml_path = workspace / 'Nordic source material' / 'tiamat-export-Current-202605081200012583.xml'
    out_path = workspace / 'Nordic source material' / 'rrb_bus_stop_locations.csv'

    if not xml_path.exists():
        sys.exit(f"ERROR: {xml_path} not found. Run extraction first.")

    print("Loading RRB quay IDs from source zips...")
    quay_ids = load_rrb_quay_ids_from_source()
    print(f"  {len(quay_ids)} unique NSR:Quay:XXXXX IDs to look up")

    if not quay_ids:
        sys.exit("ERROR: No quay IDs found. Check Source/ directory.")

    print(f"Streaming {xml_path.name} ({xml_path.stat().st_size // 1_000_000} MB)...")
    handler = QuayLocHandler(quay_ids)
    parser = xml.sax.make_parser()
    parser.setContentHandler(handler)
    parser.setFeature(xml.sax.handler.feature_namespaces, False)

    with open(xml_path, 'rb') as f:
        parser.parse(f)

    found = handler.found
    print(f"  Found {len(found)} / {len(quay_ids)} quays in the full dataset")

    missing = quay_ids - set(found.keys())
    if missing:
        print(f"  Missing ({len(missing)}):")
        for qid in sorted(missing)[:20]:
            print(f"    {qid}")
        if len(missing) > 20:
            print(f"    ... ({len(missing) - 20} more)")

    # Write CSV
    with open(out_path, 'w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=['quay_id', 'name', 'lat', 'lon', 'gml_pos'])
        w.writeheader()
        for qid in sorted(found.keys()):
            w.writerow(found[qid])

    print(f"Written: {out_path}")

    # Quick sanity: show first 5
    print("\nSample (first 5):")
    for qid in sorted(found.keys())[:5]:
        r = found[qid]
        print(f"  {qid:30s}  {r['name'][:30]:30s}  lat={r['lat']}  lon={r['lon']}")


if __name__ == '__main__':
    main()
